### ISSUE TITLE
Design a directory structure

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#125]
Copied from "Need Directory Heirarchy if we are writing 9K-36K files/day (1 round = ~1 sec, Max 4 blocks/sec). Rounds and Blocks have to be aligned."

Tech Notes:
1. How to separate by Blocks
2. Tree structure for 86400 blocks/day
3.

**Comment by jsync-swirlds** [comment]
Some confusion is evident in this description.
1. Blocks contain rounds, not the other way around
1. We will have roughly 1 block per second, which may contain arbitrary numbers of rounds (and that number may be variable from block to block).  We likely won't have more than 8-12 rounds in a single block, but that's not a guarantee.  Initial release will have one round per block.
1. We have no reason or purpose in splitting rounds from blocks.  Blocks do not need to be separated out, we receive a block header, all of the content for that block, then a block proof; blocks will not be interleaved within the stream.

As to the core question (how to store blocks in an efficient folder structure)
A trie structure based on block number may work well, and it makes finding block files later extremely efficient.  It also works well with archival ZIP files, as the ZIP can be named for the trie node name it contains, and more-or-less transparently take the place of that folder.

**Comment by AlfredoG87** [comment]
As @jsync-swirlds indicates as per recent discussions, I believe the `uncompressed zip` for consolidation of blocks in batches for definitive storage is an efficient approach. however we can still decide to have a folder structure within the zip files. I wonder if it makes sense to have zip inside of zips too... like we can "archive" to a Hourly Zip all the blocks for that `hour` and then do another "archive process" for daily archival and have a `day` zip that contains `hourly` zips and inside them the actual blocks... (not that am advocating for doing it by time, I actually like the numbers approach)

My thoughts:

1. I would like to avoid nested zip just because am not aware of possible perf impact, but am not aware of pros and cons, and more data would be good on this.
2. I like the approach of block numbers too, is a natural partition since we will be looking for them `knowing` the number before hand.

**Comment by jsync-swirlds** [comment]
I agree with point 1 that nested zip files is counter-productive.  It's pretty inexpensive to just repackage an uncompressed zip (because there is no compression/decompression involved), if we want to repack hourly to daily, daily to weekly, etc...

For what folder is _within_ the ZIP file, I would again suggest a trie based on block number.  It's already a tree structure, continues the outer folder structure (which makes repackaging easier), and will tend to naturally lend itself to variable consolidation thanks to the sequential character of block numbers and constant rate of block creation.  We might, for example choose to archive every 10,000 blocks (about 2.78 hours) to make file/folder names extra simple, and have "deep" archives consolidate to every 100,000 blocks (about 1.16 days),  1,000,000 blocks (about 11.6 days), or even 10,000,000 blocks (about 115.7 days, or 3.8 months).

example:
```
1
| -- 10
      | -- 102
            | -- 1023
                  | -- 10234.zip
                        | -- 102340
                              | -- 1023400.blk.zstd
                              | -- ...
                              | -- 1023409.blk.zstd
                        | -- 102341
                              | -- 1023410.blk.zstd
                              | -- ...
                              | -- 1023419.blk.zstd
                        | -- ...
                        | -- 102349
                              | -- 1023490.blk.zstd
                              | -- ...
                              | -- 1023499.blk.zstd
                  | -- 10235.zip
                        | -- 102341
                        | -- 102342
                        | -- ...
                        | -- 102349
            | -- 1024
                  | -- ...
etc...
```

**Comment by jasperpotts** [comment]
In my head I had similar design to @jsync-swirlds above. The change I would make is to use a basis of 1000. In my testing creating a zip of 1000 blocks seamed like a sensible size in the 100MB-1.3GB range. I would maintain the same sizing for directories with max 1000 files per directory. The block numbers are 63bit (positive signed long) so maximum block number with today's design is `9,223,372,036,854,775,807`. I would break it into directories based on 3 digits rather than the 1 digit Joseph had.

**Comment by jsync-swirlds** [comment]
> In my head I had similar design to @jsync-swirlds above. The change I would make is to use a basis of 1000. In my testing creating a zip of 1000 blocks seamed like a sensible size in the 100MB-1.3GB range. I would maintain the same sizing for directories with max 1000 files per directory. The block numbers are 63bit (positive signed long) so maximum block number with today's design is `9,223,372,036,854,775,807`. I would break it into directories based on 3 digits rather than the 1 digit Joseph had. With least significant 3 digits in zip file.
> 
> So the above block would have a path: `/blocks/9/223/372/036/854/775.zip/9223372036854775807.blk.zstd` or block 10 would have path: `/blocks/0/000/000/000/000/0.zip/0000000000000000010.blk.std`
> 
> I am open for debate on if we use preceding zero on file names, so `0.blk.std` or `0000000000000000010.blk.std`. I can see pros and cons for each.

Having managed a lot of files with and without leading zeros, I would definitely encourage including leading zeros on all folders and files in this setup.  The reason being that most filesystems sort by lexical order, and `2.zip` ends up after `10.zip`-`19.zip` (not to mention `100.zip`-`199.zip`, which also interleave with `10.zip`-`19.zip`).  To ensure that listings are easier for operations staff to work with (if/when necessary), we should include the leading zeros so that file and folder names are fixed-length values and lexical sort _matches_ numeric sort.

I, personally, prefer at least the _option_ for varying levels of aggregation (i.e. we can have a different number of blocks per zip based on age and configuration), but those are details we can pick asa fixed `1000` blocks for now, and change later if necessary

As to folder count, listing files takes time proportional to the number of entries in the directory.  I could see up to 100 per folder, but 1000 seems a bit much.  I advocate for the simplest option, one folder per digit, mostly because 16 folder levels is quite minimal in almost any modern filesystem (exFAT being the exception, but we shouldn't use that, for anything), and the uniformity makes it easy to adjust other parameters in configuration, if desired, particularly for a third-party Block Node that might store blocks filtered to their items of interest (and hence much smaller and/or more sparse than "full" block nodes).

**Comment by jasperpotts** [comment]
I think we need fixed numbers of blocks per zip and directory to get direct indexing to find a block by number without searching or external index. To handle full long size we want 26 digit file names, so 26 directories deep sounded like too much so 3 digits / 1000 or maybe 2 digits 100 seems a lot less crazy number of directories.

**Comment by jsync-swirlds** [comment]
I routinely have 20+ folder levels in my home systems, so I guess it just doesn't seem excessive to me.
As already noted, we can always just start with a fixed number of blocks per zip, and change that later only if it makes sense to do so.
I don't want to assume that we'll stick to a fixed point to zip for all time, however, as that could lock us into some very troublesome consequences eventually.  It also makes deep archives much harder if we cannot consolidate larger numbers of blocks per file when appropriate (e.g. anything over 1 year old in zip-per-year, roughly, archives).
It's also not hard to have the software check for zip files with a few assumptions; at worst it might be 4 or 5 tries to find the correct path, and even then the largest try count would be for the oldest (and therefore least accessed) blocks.

**Comment by jsync-swirlds** [comment]
Jasper:
I tested performance of splitting into directories every digit vs every 3 digits so 10 blocks per directory or 1000.  The results were surprising and not 100% conclusive. I tested on two different linux machines one with fast NVMe SSD and one with slow Spinning HD. For those intrested this was the logic for block number to path:
```java
    private static final NumberFormat NUMBER_FORMAT = new DecimalFormat("0000000000000000000");
    private static final String BLOCK_FILE_EXTENSION = ".blk";

    public static Path blockToPath(Path basePath, long blockNumber, int digitsPerDir) {
        final String blockNumberStr = NUMBER_FORMAT.format(blockNumber);
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < blockNumberStr.length(); i += digitsPerDir) {
            for (int j = 0; j < digitsPerDir && i + j < blockNumberStr.length(); j++) {
                sb.append(blockNumberStr.charAt(i + j));
            }
            if (i + digitsPerDir < blockNumberStr.length()) {
                sb.append('/');
            }
        }
        sb.append(BLOCK_FILE_EXTENSION);
        return basePath.resolve(sb.toString());
    }
```
I ignored the zipping part of the test.
This was all with ext4 file system

### Results
SSD there was clear 10% faster for 3 digits - 1000 files per directory
HD the numbers were all over the place and super slow(this was on Google VM)
![image](https://github.com/user-attachments/assets/9589e149-e8c3-4409-bd26-e719f899ae99)
Higher is better as more read operations per second, The difference in performance was crazy! :exploding_head: 500 vs 500,000!! wow NVMe SSDs are impressive
So no technical reason I can see for 3 vs 1 digit per dir, despite my gut being sure there would be :wink: .

So will leave the decision up to the team.

**Comment by jsync-swirlds** [comment]
Resolved
