### ISSUE TITLE
Find the performance bottleneck in Sprint 54/55 implementation

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#161]

**Comment by mattp-swirldslabs** [comment]
Tested sending a single block with 40k minimal block items from a client to the block node via `publishBlockStream` took ~35 secs. 35 sec latency is very far outside the target latency of less than a second.

I discovered 3 main issues:
---

1) client latency - Using `ghz` perf testing tool was taking ~15 sec. After creating a single input file with 40k block items this loaded in less than a second

2) Synchronous wait to persisting block items to the file system - ~10 secs. We were waiting to save each block item to the file system.

3) Sending a response for each `PublishSubscribeRequest`. - Remaining time spend sending 40k responses rather than a single `PublishSubscribeResponse` for the whole block.

**Comment by mattp-swirldslabs** [comment]
After commenting out the code impacting #2 and #3 (and fixing #1) I found that the block node was able to consume 40k block items in less than a second. This puts us in the expected performance range for now. I created #168 to address #2 and #3 in code.
